spring:
  datasource:
    url: jdbc:h2:mem:proddb
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    db:
      connection: "{connectionString: 'http://__', userName: 'proddb', password: '12345'}"
      host: 129.0.0.1
      port: 2400
sms:
  enabled: true
