spring:
  datasource:
    url: jdbc:h2:mem:proddb
    driverClassName: org.h2.Driver
  sql:
    init:
      mode: always
      data-locations: classpath:data-prod.sql
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    db:
      connection: "{connectionString: 'http://__', userName: 'proddb', password: '12345'}"
      host: 129.0.0.1
      port: 2400

sms:
  enabled: true