spring:
  application:
    name: ecom-project
  datasource:
    url: jdbc:h2:mem:telusko
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true